### PR TITLE
chore: @W-10145159 release v0.22.3

### PR DESCRIPTION
**Pull request by rohansroy**

### CODE REVIEW

**Review by bgrant — APPROVED** [review]
Thanks.

**Review by bgrant — CHANGES_REQUESTED** [review]
Should we get this PR into the release?

Adding Updating CODEOWNERS with ECCN as per Export Control Compliance by svc-scm · Pull Request #66 · salesforce/django-declarative-apis

**Comment by bgrant** [comment]
All tests pass locally.

**Comment by rohansroy** [comment]
@bgrant I can do that, will require a little git work.

**Review by bgrant — APPROVED** [review]

**Pull request merged**
